In [6]:
# import TM_catalyst_framework.metal_template as template
# import the package
import os # package for reading, creating and saving files or directories
from TM_catalyst_framework import Template, Complex, Ligand, GeoOpt, QChem

Template().options()

tetrahedral
octahedral
trigonal_planar
square_pyramidal
trigonal_bipyramidal


In [7]:
from openbabel import openbabel as ob
from openbabel import pybel
import numpy as np
""" Create a metal complex with a titanium center with trigonal bipyramidal geometry using Open Babel """

placeholder_map: dict = {
                    1:2,# helium at position 1
                    2:10, # neon at position 2
                    3:18, # Argon at position 3
                    4:36, # Kr at position 4
                    5:54, # Xe at position 5
                    6:86, # Rn at position 6
                    7:118  # Og at position 7
                    #8: 
                    #9:
                }

mol = ob.OBMol()

# Create metal center and set properties (atomic number, charge, multiplicity, coordinates)
metal = mol.NewAtom()
metal.SetAtomicNum(22)  # Titanium
metal.SetVector(0.0, 0.0, 0.0)

bondlength = 2 # approximate Ti-C bond length in angstroms

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder1 = mol.NewAtom()
placeholder1.SetAtomicNum(placeholder_map[1])  # Placeholder atom
placeholder1.SetVector(0.0, 0.0, bondlength)
mol.AddBond(1,2,1)

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder2 = mol.NewAtom()
placeholder2.SetAtomicNum(placeholder_map[2])  # Placeholder atom
placeholder2.SetVector(bondlength, 0.0, 0.0)
mol.AddBond(1,3,1)


# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder3 = mol.NewAtom()
placeholder3.SetAtomicNum(placeholder_map[3])  # Placeholder atom
x = -bondlength * np.cos(np.pi/3)
y = -bondlength * np.sin(np.pi/3)
placeholder3.SetVector(x, y, 0.0)
mol.AddBond(1,4,1)

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder4 = mol.NewAtom()
placeholder4.SetAtomicNum(placeholder_map[4])  # Placeholder atom
x = -bondlength * np.cos(np.pi/3)
y = bondlength * np.sin(np.pi/3)
placeholder4.SetVector(x, y, 0.0)
mol.AddBond(1,5,1)


# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder5 = mol.NewAtom()
placeholder5.SetAtomicNum(placeholder_map[5])  # Placeholder atom
placeholder5.SetVector(0.0, 0.0, -bondlength)
mol.AddBond(1,6,1)

print(f"Number of atoms: {mol.NumAtoms()}")
print(f"Number of bonds: {mol.NumBonds()}")


Number of atoms: 6
Number of bonds: 5


In [8]:
# Alternatively, you can also use the mol_visual module to view the 3D strucutre of the sdf file 
from TM_catalyst_framework.io_utils import mol_visual
mol_3d = mol_visual.visualize_mol_molecule(mol, displaystyle="stick", label_atoms=True)
mol_3d

mol provided is invalid:, trying openbabel mol routine...


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [4]:
# add template to metal template class
template = Template()
template.add_template(mol, 
                      template_name="trigonal_bipyramidal"
                      )

In [13]:
""" Create a metal complex with a titanium center 
with trigonal planar geometry using Open Babel """

mol = ob.OBMol()

# Create metal center and set properties (atomic number, charge, multiplicity, coordinates)
metal = mol.NewAtom()
metal.SetAtomicNum(22)  # Titanium
metal.SetVector(0.0, 0.0, 0.0)

bondlength = 2 # approximate Ti-C bond length in angstroms

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder1 = mol.NewAtom()
placeholder1.SetAtomicNum(placeholder_map[1])  # Placeholder atom
placeholder1.SetVector(bondlength, 0.0, 0.0)
mol.AddBond(1,2,1)


# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder2 = mol.NewAtom()
placeholder2.SetAtomicNum(placeholder_map[2])  # Placeholder atom
x = -bondlength * np.cos(np.pi/3)
y = -bondlength * np.sin(np.pi/3)
placeholder2.SetVector(x, y, 0.0)
mol.AddBond(1,3,1)

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder3 = mol.NewAtom()
placeholder3.SetAtomicNum(placeholder_map[3])  # Placeholder atom
x = -bondlength * np.cos(np.pi/3)
y = bondlength * np.sin(np.pi/3)
placeholder3.SetVector(x, y, 0.0)
mol.AddBond(1,4,1)

print(f"Number of atoms: {mol.NumAtoms()}")
print(f"Number of bonds: {mol.NumBonds()}")

# add template to metal template class
template = Template()
template.add_template(mol, 
                      template_name="trigonal_planar"
                      )

Number of atoms: 4
Number of bonds: 3


In [14]:
mol_3d = mol_visual.visualize_mol_molecule(mol, displaystyle="stick", label_atoms=True)
mol_3d

mol provided is invalid:, trying openbabel mol routine...


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [15]:
""" Create a metal complex with a titanium center 
with square pyramidal geometry using Open Babel """

mol = ob.OBMol()

# Create metal center and set properties (atomic number, charge, multiplicity, coordinates)
metal = mol.NewAtom()
metal.SetAtomicNum(22)  # Titanium
metal.SetVector(0.0, 0.0, 0.0)

bondlength = 2 # approximate Ti-C bond length in angstroms

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder1 = mol.NewAtom()
placeholder1.SetAtomicNum(placeholder_map[1])  # Placeholder atom
placeholder1.SetVector(0.0, 0.0, bondlength)
mol.AddBond(1,2,1)

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder2 = mol.NewAtom()
placeholder2.SetAtomicNum(placeholder_map[2])  # Placeholder atom
placeholder2.SetVector(bondlength, 0.0, 0.0)
mol.AddBond(1,3,1)


# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder3 = mol.NewAtom()
placeholder3.SetAtomicNum(placeholder_map[3])  # Placeholder atom
placeholder3.SetVector(0, -bondlength, 0.0)
mol.AddBond(1,4,1)

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder4 = mol.NewAtom()
placeholder4.SetAtomicNum(placeholder_map[4])  # Placeholder atom
placeholder4.SetVector(-bondlength, 0.0, 0.0)
mol.AddBond(1,5,1)


# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder5 = mol.NewAtom()
placeholder5.SetAtomicNum(placeholder_map[5])  # Placeholder atom
placeholder5.SetVector(0.0, bondlength, 0.0)
mol.AddBond(1,6,1)

print(f"Number of atoms: {mol.NumAtoms()}")
print(f"Number of bonds: {mol.NumBonds()}")
mol_3d = mol_visual.visualize_mol_molecule(mol, displaystyle="stick", label_atoms=True)
mol_3d
# add template to metal template class
template = Template()
template.add_template(mol, 
                      template_name="square_pyramidal"
                      )

Number of atoms: 6
Number of bonds: 5
mol provided is invalid:, trying openbabel mol routine...


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [16]:
""" Create a metal complex with a titanium center 
with octahedral geometry using Open Babel """

mol = ob.OBMol()

# Create metal center and set properties (atomic number, charge, multiplicity, coordinates)
metal = mol.NewAtom()
metal.SetAtomicNum(22)  # Titanium
metal.SetVector(0.0, 0.0, 0.0)

bondlength = 2 # approximate Ti-C bond length in angstroms

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder1 = mol.NewAtom()
placeholder1.SetAtomicNum(placeholder_map[1])  # Placeholder atom
placeholder1.SetVector(0.0, 0.0, bondlength)
mol.AddBond(1,2,1)

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder2 = mol.NewAtom()
placeholder2.SetAtomicNum(placeholder_map[2])  # Placeholder atom
placeholder2.SetVector(bondlength, 0.0, 0.0)
mol.AddBond(1,3,1)


# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder3 = mol.NewAtom()
placeholder3.SetAtomicNum(placeholder_map[3])  # Placeholder atom
placeholder3.SetVector(0, -bondlength, 0.0)
mol.AddBond(1,4,1)

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder4 = mol.NewAtom()
placeholder4.SetAtomicNum(placeholder_map[4])  # Placeholder atom
placeholder4.SetVector(-bondlength, 0.0, 0.0)
mol.AddBond(1,5,1)

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder5 = mol.NewAtom()
placeholder5.SetAtomicNum(placeholder_map[5])  # Placeholder atom
placeholder5.SetVector(0.0, bondlength, 0.0)
mol.AddBond(1,6,1)

# Create placeholder atoms and set properties (atomic number, coordinates)
placeholder6 = mol.NewAtom()
placeholder6.SetAtomicNum(placeholder_map[6])  # Placeholder atom
placeholder6.SetVector(0.0, 0.0, -bondlength)
mol.AddBond(1,7,1)

print(f"Number of atoms: {mol.NumAtoms()}")
print(f"Number of bonds: {mol.NumBonds()}")
mol_3d = mol_visual.visualize_mol_molecule(mol, 
                                           displaystyle="stick", label_atoms=True)
mol_3d
# add template to metal template class
template = Template()
template.add_template(mol, 
                      template_name="octahedral"
                      )

Number of atoms: 7
Number of bonds: 6
mol provided is invalid:, trying openbabel mol routine...


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [17]:
import numpy as np

def generate_tetrahedral_coordinates(bond_length):
    """
    Generate coordinates for a tetrahedral structure with the central atom at (0, 0, 0)
    and four surrounding atoms at equal bond lengths 'bond_length'.
    
    The bond angle between any two bonds is approximately 109.5 degrees.
    
    Returns:
    - A NumPy array of shape (5, 3) where the first row is the central atom,
      and the next four rows are the surrounding atoms.
    """
    # Scaling factor to achieve the desired bond length
    scale = bond_length / np.sqrt(3)
    
    # Unscaled coordinates for the four vertices of the tetrahedron
    vertices = np.array([
        [1, 1, 1],
        [1, -1, -1],
        [-1, -1, 1],
        [-1, 1, -1]
    ])
    
    # Scale the vertices
    scaled_vertices = vertices * scale
    
    # Central atom at origin
    central_atom = np.array([0, 0, 0])
    
    # Combine all coordinates
    all_coordinates = np.vstack([central_atom, scaled_vertices])
    
    return all_coordinates

# Example usage:
bondlength = 2.0  # Example bond length
coords = generate_tetrahedral_coordinates(bondlength)
print("Central atom and four surrounding atoms coordinates:")
print(coords)


""" Create a metal complex with a titanium center 
with tetrahedral geometry using Open Babel """

mol = ob.OBMol()

# Create metal center and set properties (atomic number, charge, multiplicity, coordinates)
metal = mol.NewAtom()
metal.SetAtomicNum(22)  # Titanium
metal.SetVector(coords[0, 0], coords[0, 1], coords[0, 2])

for i in range(1, 5):
    placeholder = mol.NewAtom()
    placeholder.SetAtomicNum(placeholder_map[i])  # Placeholder atom
    placeholder.SetVector(coords[i, 0], coords[i, 1], coords[i, 2])
    mol.AddBond(1, i + 1, 1)


print(f"Number of atoms: {mol.NumAtoms()}")
print(f"Number of bonds: {mol.NumBonds()}")

from TM_catalyst_framework.io_utils import mol_visual

mol_3d = mol_visual.visualize_mol_molecule(mol, displaystyle = "stick", 
                                           label_atoms=True)
mol_3d


Central atom and four surrounding atoms coordinates:
[[ 0.          0.          0.        ]
 [ 1.15470054  1.15470054  1.15470054]
 [ 1.15470054 -1.15470054 -1.15470054]
 [-1.15470054 -1.15470054  1.15470054]
 [-1.15470054  1.15470054 -1.15470054]]
Number of atoms: 5
Number of bonds: 4
mol provided is invalid:, trying openbabel mol routine...


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [18]:
# add template to metal template class
template = Template()
template.add_template(mol, 
                      template_name="tetrahedral"
                      )